# Generated by Django 2.0.3 on 2018-07-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstgis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
    ]
