# Generated by Django 2.0.3 on 2018-07-25 05:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstgis', '0003_auto_20180725_0150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incidences',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
