# Generated by Django 2.0.3 on 2018-07-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstgis', '0007_countie'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incidences',
            managers=[
            ],
        ),
    ]
